apiVersion: v1
kind: ConfigMap
metadata:
  # ConfigMap의 이름을 정합니다.
  name: api-gateway-service-config
data:
  # --- 이 부분에 application.yml의 내용을 그대로 붙여넣습니다 ---
  # 'application.yml' 이라는 이름의 키(key)로 파일 내용을 저장합니다.
  application.yml: |-
    server:
      shutdown: graceful
      servlet:
        context-path: /
      forward-headers-strategy: framework
    
    spring:
      lifecycle:
        timeout-per-shutdown-phase: 30s

      cloud:
        kubernetes:
          discovery:
            primary-port-name: tcp-clients
            enabled: true
    
        gateway:
          default-filters:
            - PreserveHostHeader
          server:
            webflux:
              forwarded:
                enabled: true
              x-forwarded:
                enabled: true
              globalcors:
                cors-configurations:
                  '[/**]':
                    allowedOrigins: 
                      - "http://localhost:5173"
                      - "https://gearfirst-fe.vercel.app/"
                    allowedMethods: "*"
                    allowedHeaders: "*"
                    allowCredentials: true 
              discovery:
                locator:
                  enabled: true
              routes:
                - id: receipt-service-route
                  # "lb"는 "Load Balancer"의 약자입니다.
                  # 쿠버네티스 내부의 Service 이름(parts-service)을 찾아가라는 뜻입니다.
                  uri: lb://receipt-service
                  predicates:
                  # 외부에서 /parts/ 로 시작하는 모든 요청은 이 규칙을 따릅니다.
                    - Path=/receipt/**
        
                - id: order-service-route
                  uri: lb://order-service
                  predicates:
                    - Path=/order/**
                  filters:
                    - StripPrefix = 1 #"/order"부분 제거하고 내부로 전달
        
                - id: inventory-service-route
                  uri: lb://inventory-service
                  predicates:
                    - Path=/inventory/**
      
                - id: warehouse-service-route
                  uri: lb://warehouse-service
                  predicates:
                    - Path=/warehouse/**
      
                - id: user-service-route
                  uri: lb://user-service
                  predicates:
                    - Path=/user/**
    
      loadbalancer:
        ribbon: 
          enabled: false
    
    management:
      endpoint:
        health:
          probes:
            enabled: true
      endpoints:
        web:
          exposure:
            include: health,info