apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: api-gateway-backend-config
spec:
  connectionDraining:
    drainingTimeoutSec: 50
  healthCheck:
    # 헬스 체크를 보낼 경로를 지정합니다.
    requestPath: /actuator/health
    # 헬스 체크를 보낼 포트를 지정합니다.
    port: 8080