apiVersion: v1
kind: Service
metadata:
  name: auth-service-mobile
  annotations:
    cloud.google.com/backend-config: '{"ports": {"80":"auth-backend-config"}}'
spec:
  selector:
    app: auth-service-mobile   # ✅ mobile deployment의 label과 동일해야 함
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
