apiVersion: apps/v1
kind: Deployment
metadata:
  # 이 Deployment의 이름을 정합니다.
  name: user-service-deployment
spec:
  # 동일한 Pod를 몇 개 실행할지 정합니다. 우선 1개로 시작합니다.
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # 업데이트 중 최대 25%의 Pod가 사용 불가능해도 됨 (replicas:1 -> 0개로 계산)
      maxUnavailable: 0
      # 업데이트 중 목표보다 최대 25%의 Pod를 더 만들어도 됨 (replicas:1 -> 1개로 계산)
      maxSurge: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        # 이 Pod의 이름표입니다. Service가 이 Pod를 찾아올 때 사용됩니다.
        app: user-service
    spec:
      volumes:
        - name: config-volume
          configMap:
            # 'parts-service-config' 라는 이름의 ConfigMap을 사용합니다.
            name: user-service-config

      serviceAccountName: default

      terminationGracePeriodSeconds: 60 # Pod 종료 멈춤 문제 방지를 위해 유예시간 설정

      containers:
        - name: user-service-container
          # --- [중요] ---
          # 방금 push한 Docker 이미지의 전체 주소를 여기에 정확하게 입력합니다.
          image: asia-northeast1-docker.pkg.dev/gearfirst/gearfirst-docker-repo/user-service:v2.0
          ports:
            # 스프링 부트 애플리케이션이 사용하는 포트입니다. (보통 8080)
            - containerPort: 8080
                # DB 비밀번호를 Secret에서 가져와 환경변수로 설정

          readinessProbe:
            httpGet:
              # Kubernetes 전용 readiness 경로 사용
              path: /user/actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
              # Kubernetes 전용 liveness 경로 사용
              path: /user/actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10

          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloud-sql-credentials
                  key: password
            - name: SPRING_CONFIG_LOCATION
              value: file:/config/application.yml
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "gearfirst-kafka-cluster-kafka-bootstrap.default.svc:9092"

          volumeMounts:
            - name: config-volume
              # 컨테이너 내부의 '/config' 폴더에 연결합니다.
              mountPath: /config

          # --- 2. Cloud SQL 인증 프록시 사이드카 컨테이너 추가 ---
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.0
          args:
            - "--structured-logs"
            # [INSTANCE_CONNECTION_NAME]을 아래 명령어로 확인하여 붙여넣으세요.
            - "gearfirst:asia-northeast1:gearfirst-db-instance"
          securityContext:
            runAsNonRoot: true